name: Deploy to EC2
on:
    push:
        branches:
            - main
jobs:
    build:
        steps:
            - name: Build project
              run: echo "Building project"
    push:
        steps:
            - name: Push project to ecr
              run: echo "Project being pushed to ecr"
    deploy:
        steps:
            - name: Deploy project to ec2
              run: echo "Deploy project to ec2 server"