name: Deploy to EC2
on:
    push:
        branches:
            - main

env:
    DOTNET_CONFIGURATION: release
    AWS_REGION: eu-west-2
    AWS_ACCESS_KEY: ${{secrets.ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.ACCESS_SECRET_KEY}}

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
        
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.103'

            - name: Build project and run tests
              run: | 
                dotnet build -c $DOTNET_CONFIGURATION
                echo "build successful"
                echo "running tests...."
                echo "test completed"
    push:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            
            - name: Configure credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::533267394084:role/github-role-stack-Role-RxDfMY7SMkYZ
                aws-region: ${{env.AWS_REGION}}

            - name: Login to ECR repo
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag and push image to ecr
              env:
                REGISTRY: ${{steps.login-ecr.outputs.registry}}
                REPOSITORY: books-repo
                IMAGE_TAG: ${{github.sha}}
              run: |-
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

            - name: Deploy to EC2
              env:
                REPOSITORY: books-repo
                IMAGE_TAG: ${{github.sha}}
                EC2_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                HOSTNAME: ${{secrets.HOST_DNS}}
                USER_NAME: ${{secrets.USERNAME}}
              uses: appleboy/ssh-action@v1.1.0
              with:
                host: ${{env.HOSTNAME}}
                port: 22
                key: ${{env.EC2_PRIVATE_KEY}}
                username: ${{env.USER_NAME}}
                envs: EC2_PRIVATE_KEY, REGISTRY, REPOSITORY, IMAGE_TAG, AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, AWS_REGION
                script: |-
                    echo "in ec2 server"